### ISSUE TITLE
Aprender a utilizar API SEI

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/handbook#62]
- Documentação recebida: [SEI WebServices](https://github.com/automatiza-mg/handbook/files/14113048/SEI-WebServices-v40.3._240130_172029.pdf).
- O vídeo [How to do SOAP API requests in Python](https://www.youtube.com/watch?v=2FDNQ5w1tDY) dá uma ótima introdução de como utilizar uma API SOAP.
- O artigo [REST vs. SOAP](https://www.redhat.com/en/topics/integration/whats-the-difference-between-soap-rest) mostra diferenças conceituais entre SOAP e REST APIs.

**Comment by gabrielbdornas** [comment]
## Reunião Sub Digital

- Explicações Luiz e Fernanda:
  - Web-service do SEI realiza comunicação via SOAP. Hoje o ip é utilizado como chave de acesso.
  - Não trabalha atualmente com geração de tokens, mas seria necessário realizar testes para geração.
  - Configurações de acesso aos endpoints da API serão feitos no login de um usuário. Esta liberação poderá ser feita para todos ou para unidades específicas.
  - Turma do SIAD (SEPLAG) já realizou esta integração e podemos conversar com eles. Documento nascendo de outro sistema. Fernanda irá organizar uma agenda mais técnica.
  - Ambiente de homologação disponível para testes.

**Comment by gabrielbdornas** [comment]
Código do vídeo [How to do SOAP API requests in Python](https://www.youtube.com/watch?v=2FDNQ5w1tDY) testado e funcionando no terminal:

```
# necessário criar ambiente virtual e instalar lib requests via `pip install requests`

# main.py file
import requests
import xml.etree.ElementTree as ET

celsius_temp = 20

url = 'https://www.w3schools.com/xml/tempconvert.asmx'

SOAPEnvelope = f'''
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.>
  <soap:Body>
    <CelsiusToFahrenheit xmlns="https://www.w3schools.com/xml/">
      <Celsius>{celsius_temp}</Celsius>
    </CelsiusToFahrenheit>
  </soap:Body>
</soap:Envelope>'''

options = {
        'Content-Type': 'text/xml; charset=utf-8',
}

response = requests.post(url, data = SOAPEnvelope, headers = options)

root = ET.fromstring(response.text)

for child in root.iter('{https://www.w3schools.com/xml/}CelsiusToFahrenheitResult'):
        C2F = child.text

print(f'{celsius_temp} Celsius is {C2F} Fahrenheit')
```

O vídeo [Calling SOAP Web Services in Power Automate Desktop](https://www.youtube.com/watch?v=hIfnzEfRnZM) mostra como executar a mesma chamada utilizando Power Automate. Recebi o mesmo erro de proxy relatado em [neste issue](https://github.com/automatiza-mg/automatizacoes/issues/118).

**Comment by gabrielbdornas** [comment]
> Um pequeno problema é a utilização de validação via IP e não token.

[Esta resposta Stackoverflow](https://stackoverflow.com/a/54935038/11755155) mostra um exemplo para autenticação, mas quanto tentei utilizar recebi o erro: `zeep.exceptions.Fault: Serviço [NOME-SERVICO] do sistema [NOME-SISTEMA] não possui autenticação por Endereço.`

**Comment by gabrielbdornas** [comment]
[Esta](https://stackoverflow.com/questions/76392468/how-can-i-add-an-authentication-header-to-a-soap-request-using-zeep-in-python) pode ser uma boa pergunta para responder quando conseguir solucionar o problema de autenticação.

**Comment by gabrielbdornas** [comment]
@YanVieira1905, os testes feitos até o momento podem ser observados [neste arquivo](https://github.com/automatiza-mg/api-sei-segov/blob/main/testes_gabriel/main.py).

**Comment by gabrielbdornas** [comment]
> [Esta resposta Stackoverflow](https://stackoverflow.com/a/54935038/11755155) mostra um exemplo para autenticação, mas quanto tentei utilizar recebi o erro: `zeep.exceptions.Fault: Serviço [NOME-SERVICO] do sistema [NOME-SISTEMA] não possui autenticação por Endereço.`

Em testes com Edimilson, chegamos à conclusão que a opção de utilizar o token não está funcionando pois ao habilitar a  autentiação via Endereço IP o erro mudou para `zeep.exceptions.Fault: Acesso negado.`:

```
Traceback (most recent call last):
  File "/home/gabrielbdornas/code/automatiza-mg/api-sei-segov/testes_gabriel/main.py", line 116, in <module>
    print(teste_listar_marcadores_unidade())
  File "/home/gabrielbdornas/code/automatiza-mg/api-sei-segov/testes_gabriel/main.py", line 40, in teste_listar_marcadores_unidade
    response = client.service.listarMarcadoresUnidade(**dict_call)
  File "/home/gabrielbdornas/code/automatiza-mg/api-sei-segov/testes_gabriel/venv/lib/python3.10/site-packages/zeep/proxy.py", line 46, in __call__
    return self._proxy._binding.send(
  File "/home/gabrielbdornas/code/automatiza-mg/api-sei-segov/testes_gabriel/venv/lib/python3.10/site-packages/zeep/wsdl/bindings/soap.py", line 135, in send
    return self.process_reply(client, operation_obj, response)
  File "/home/gabrielbdornas/code/automatiza-mg/api-sei-segov/testes_gabriel/venv/lib/python3.10/site-packages/zeep/wsdl/bindings/soap.py", line 229, in process_reply
    return self.process_error(doc, operation)
  File "/home/gabrielbdornas/code/automatiza-mg/api-sei-segov/testes_gabriel/venv/lib/python3.10/site-packages/zeep/wsdl/bindings/soap.py", line 329, in process_error
    raise Fault(
zeep.exceptions.Fault: Acesso negado.
```

Ficamos em dúvida sobre a utilização dos parâmetros `SiglaSistema`, `IdentificacaoServico`e `IdUnidade` está correto, mas consultando o [código SEGOV](https://github.com/automatiza-mg/handbook/issues/62#issuecomment-2073453932), acredito que estou no caminho certo.

**Comment by gabrielbdornas** [comment]
@YanVieira1905, em 30/04/2024, após reunião com Edimilson e Luiz (PRODEMGE), consegui fazer a primeira chamada na API que funcionou, registrada [neste commit](https://github.com/automatiza-mg/api-sei-segov/blob/82525cfae8b289f10820870272c2d7a2638041ee/testes_gabriel/testes_luis_suds.py). **Necessário aperfeiçoar o modo de incluir o token na chamada** e testar outros métodos.

**Comment by gabrielbdornas** [comment]
> [@YanVieira1905](https://github.com/YanVieira1905), em 30/04/2024, após reunião com Edimilson e Luiz (PRODEMGE), consegui fazer a primeira chamada na API que funcionou, registrada [neste commit](https://github.com/automatiza-mg/api-sei-segov/blob/82525cfae8b289f10820870272c2d7a2638041ee/testes_gabriel/testes_luis_suds.py). **Necessário aperfeiçoar o modo de incluir o token na chamada** e testar outros métodos.

@YanVieira1905, após reunião com Edimilson e Luiz (Prodemge) conseguimos fazer a autenticação utilizando o token.

Luiz encontrou  este  [Manual do Webservice do Módulo Peticionamento](https://github.com/anatelgovbr/mod-sei-peticionamento/blob/master/sei/web/modulos/peticionamento/ws/manual_ws_peticionamento.md), onde tem a explicação de onde o token deve ser informado na chamada:

> IdentificacaoServico	: Valor informado no cadastro do Serviço **ou a Chave de Acesso correspondente para o Sistema cliente no SEI no menu Administração** > Sistemas. Próxima versão do SEI somente aceitará integrações por Chave de Acesso.

Um ponto negativo foi que descobrimos não haver um endpoint para listar todos os processos de uma unidade. Isto deve se justificar pela possibilidade de haver, para algumas unidades, vários processos.

Necessário agora testar como um processo restrito é retornado na chamada do endpoint `consultarProcedimento`.
